apiVersion: apps/v1
kind: Deployment
metadata:
        name: test2
spec:
        replicas: 2
        selector:
                matchExpressions:
                        - key: app
                          operator: In
                          values:
                                - test
        template:
                metadata:
                        name: test
                        labels:
                                app: test
                spec:
                        containers:
                                - image: olegsir/test-nginx
                                  name: test-nginx
                                  ports:
                                         - containerPort: 80
                                           protocol: TCP

--- 
apiVersion: v1
kind: Service
metadata:
        name: test
        namespace: default
spec:
        ports:
                - port: 80
                  targetPort: 80
        selector:
                app: test

